<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-03-26T15:39:32+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'pt_PT',
    'version_installed' => '9.3.9',
    'version_db_installed' => '20241115093300',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1743000903,
        'latest_version' => '9.3.9',
    ],
    'email' => [
        'default' => [
            'address' => 'pedro@nitrogenio.net',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
];
