<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-04-11T12:20:46+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.last_cleared
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'pt_PT',
    'version_installed' => '9.3.9',
    'version_db_installed' => '20241115093300',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1743000903,
        'latest_version' => '9.3.9',
    ],
    'email' => [
        'default' => [
            'address' => 'pedro@nitrogenio.net',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
    'cache' => [
        'last_cleared' => 1744374046,
        'blocks' => false,
        'assets' => false,
        'theme_css' => true,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_block' => false,
        'clear' => [
            'thumbnails' => false,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ],
];
